branch-defaults:
  main:
    environment: Meme-maker-github
    group_suffix: null
global:
  application_name: meme-maker
  branch: null
  default_ec2_keyname: null
  default_platform: Corretto 17
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
deploy:
  artifact: target/meme-maker-1.1.0.jar