name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
      - eb

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: |
          mvn clean install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure Elastic Beanstalk CLI
        run: |
          sudo apt-get -y install python3-pip
          pip3 install --upgrade pip
          pip3 install awsebcli

      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy ${{ secrets.EB_ENV_NAME }}
          eb setenv PORT=8080